/** @type {import('tailwindcss').Config} */
//
// Color ramps (v6 rebuild) — see README.md "디자인 시스템" v6 notes for the full writeup.
//
// Every ramp below (primary/slate/red/green/amber) was generated by a one-off OKLCH script
// (not shipped in this repo — see the v6 README note for where it lives), NOT eyeballed:
// each numbered step (50/100/.../900) targets the SAME OKLCH lightness across every hue, so
// e.g. slate-100 and red-100 now have comparable contrast against white instead of the
// wildly different ratios you get from picking hex values by eye per hue. Chroma is clamped
// per lightness/hue to the sRGB gamut boundary before converting to hex, and every hex was
// verified by converting back to OKLCH and checking it lands on its target L.
//
// Exception: `amber` (this app's warning color) deliberately does NOT share the generic
// lightness curve — forcing "dark yellow" to the same L as blue/red/green at dark steps
// makes it read as muddy brown, so amber's dark steps are held lighter (and its chroma is
// capped lower) than the shared curve would put them, tuned + re-checked separately. This is
// the same "don't blindly force uniform math onto every hue" exception this project's Figma
// docs already made for badge-text contrast in v3 (see README v3 notes).
//
// These four families (slate/red/green/amber) OVERRIDE Tailwind's built-in palettes of the
// same name — components already reference `text-slate-600`, `bg-green-100`,
// `text-amber-700`, etc. directly, so overriding the built-in keys applies the new,
// perceptually-consistent ramp to every existing screen with zero className changes.
// `primary` (this app's brand blue) stays a separate custom key, as before.
//
// Semantic layer: this project intentionally does NOT add a parallel `fill`/`text`/`border`
// Tailwind color namespace on top of these primitives — for a one-person, one-Tailwind-config
// project that would just be the same hex values duplicated under two sets of keys to keep in
// sync by hand. Instead, the Target × Role × Variant semantic naming lives as a *documented
// convention* mapping semantic names to these primitive classes — see CONVENTIONS.md's
// "스타일 (Tailwind)" section.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // brand — Target×Role "fill/brand", "text/brand" etc. (see CONVENTIONS.md)
        primary: {
          50: '#f2f7ff',
          100: '#e3eeff',
          200: '#c3dbff',
          300: '#96bfff',
          400: '#629fff',
          500: '#3480f4',
          600: '#1864d2',
          700: '#024aaa',
          800: '#00347d',
          900: '#001f51',
        },
        // neutral — Target×Role "*/neutral" (overrides Tailwind's default `slate`)
        slate: {
          50: '#f5f7fa',
          100: '#eaedf1',
          200: '#d5d9df',
          300: '#b9bec4',
          400: '#9ba0a7',
          500: '#80858c',
          600: '#666b71',
          700: '#4d5257',
          800: '#363a3e',
          900: '#212326',
        },
        // status-error — Target×Role "*/status-error" (overrides Tailwind's default `red`)
        red: {
          50: '#fff4f3',
          100: '#ffe6e5',
          200: '#ffcac8',
          300: '#ff9f9e',
          400: '#fe676c',
          500: '#e04650',
          600: '#bd2839',
          700: '#980f25',
          800: '#700016',
          900: '#48000b',
        },
        // status-success — Target×Role "*/status-success" (overrides Tailwind's default `green`)
        green: {
          50: '#e4ffea',
          100: '#c4fed2',
          200: '#a1eeb5',
          300: '#77d693',
          400: '#4cb971',
          500: '#229d55',
          600: '#00803f',
          700: '#00622f',
          800: '#004620',
          900: '#002c11',
        },
        // status-warning — Target×Role "*/status-warning" (overrides Tailwind's default
        // `amber`) — the "dark yellow" exception ramp, see file header comment above
        amber: {
          50: '#fff1df',
          100: '#ffdfb4',
          200: '#f5c480',
          300: '#e3aa54',
          400: '#cf9027',
          500: '#b57a00',
          600: '#976500',
          700: '#7d5200',
          800: '#674300',
          900: '#573901',
        },
      },
      fontFamily: {
        sans: [
          'Pretendard Variable',
          'Pretendard',
          '-apple-system',
          'BlinkMacSystemFont',
          'system-ui',
          'Roboto',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
}
